package FinanceCommon;

public class FinanceVariables {
	
	/*public static String MemberUsername="(T)224939";
	public static String MemberPassword="(T)224939";
	public static String AdminUsername="DEMO_14";
	public static String AdminPassword="DEMO_14";
	public static String OwnerBlock="Ratna";
	public static String OwnerApartmentNo="3";
	public static String TenantBlock="Ratna";
	public static String TenantApartmentNo="1";*/
	public static String UsernameId="UserName";
	public static String PasswordId="Password";
	public static String TermsAndConditions="TnC";
	public static String SignIn="logsave";
	public static String Application=".//*[@id='bs-example-navbar-collapse-1']/ul/li[2]/span/a";
	public static String URL="https://test-itsmyaccount.azurewebsites.net/Login";
	public static String MyFacilities=".//*[@id='111']/div/img";
	public static String AddFacility="Add";
	public static String FacilityNameId="FacilityName";
	public static String ContactPersonId="ContactPerson";
	public static String ContactNumberId="ContactNumber";
	public static String AllowForBookingId="IsBookingAllowed";
	public static String paidId="IsPaid";
	public static String MinimumHoursId="M1";
	public static String HourlyAmountId="Amt1";
	public static String CalculationType=".//*[@id='TypeOfDueDate']";
	public static String DueDateType="Number of Days from billing date";
	public static String DueDateType1="End Of month";
	
	public static String DueType2="Number of Days from booking date";
	public static String DueDate=".//*[@id='DueDate']";
	public static String FacilitySave=".//*[@id='Facility']/div/div[3]/button[1]";
	public static String FacilitySearchGridID="searchgrid";
	public static String FacilityGridSearchType="//option[contains(.,'Facility Name')]";
	public static String FacilityGridSearchTxtbox="jqg1";
	public static String GridSeachFindid="fbox_Grid_search";
	public static String GridSearchClose=".//*[@id='searchhdfbox_Grid']/a/span";
	public static String FacilityBookOrCancel=".//*[@id='1']/td[12]/a/button";
	public static String FacilityBookID="Add";
	public static String FacilityFromTimeId="FromTime";
	public static String FacilityToTimeId="ToTime";
	public static String FacilityDescriptionId="xDescription";
	public static String FacilityFinalBook=".//*[@id='FacilityBooking']/div/div[3]/button[2]";
	public static String FinanceVouchers=".//*[@id='503']/div/img";
	public static String GridSearch=".//*[@id='searchgrid']";
	public static String GridSearchType="//option[contains(.,'Header Reference')]";
	public static String GridSearchCompare="//option[contains(.,'begins with')]";
	public static String GridSearchTxtboxId="jqg2";
	public static String FacilitySearchKeyword="FIG";
	
	
	public static String HeaderReferenceTabInFinanceVouchers=".//*[@id='1']/td[6]";
	public static String DuedateTabInFinanceVouchers=".//*[@id='1']/td[11]";
	public static String VoucherdateTabInFinanceVouchers=".//*[@id='1']/td[4]";
	public static String VoucherNumberTabInFinanceVouchers=".//*[@id='1']/td[3]";
	public static String CloseVocherInFinanceVouchers=".//*[@id='Voucher']/div/div/div[1]/button";
	public static String CreatedOndateTabInFinanceVouchers=".//*[@id='1']/td[15]";
	public static String AmountOndateTabInFinanceVouchers=".//*[@id='1']/td[7]";
	public static String ClearingReferenceTabInFinanceVouchers=".//*[@id='1']/td[12]";
	public static String FinanceReports=".//*[@id='506']/div/img";
	public static String MemberReports="html/body/div[1]/div/div/ul/li/b[6]/a";
	public static String AmountInMemberDashboard=".//*[@id='SocietyAdmin']/div[1]/div[1]/div/div[2]/div/div[2]/a";
	public static String MemberMyAccount=".//*[@id='801']/div/img";
	public static String MemberNetBalance=".//*[@id='NET']";
	public static String LogOut=".//*[@id='bs-example-navbar-collapse-1']/ul/li[5]/span/a";
	public static String MemberReportGridSearchTxtbox=".//*[@class='input-elm']";
	public static String SocietyInvoicing =".//*[@id='504']/div/img";
	public static String FixedInvoicing="Fixed";
	public static String InvoiceDate=".//*[@id='InvoiceDate']";
	public static String InvoiceDuedate=".//*[@id='DueDate']";
	public static String SelectBlock=".//*[@id='auto_BlockID']";
	public static String SelectApartment="auto_ApartmentID";
	public static String InvoiceAmount="BA1";
	public static String InvoiceTax1=".//*[@id='CH1']";
	public static String InvoiceTax2=".//*[@id='CH2']";
	public static String OpeningBalance=".//*[@id='OPB1']";
	public static String narration="x1";
	public static String InvoiceGenerate="Gen";
	public static String InvoiceGeneratePopup="Generate";
	public static String InvoiceGenerateFinal=".//*[@id='GenInv']";
	public static String FixedInvoiceTenantAmount="BAT1";
	public static String FixedInvoiceReversal="html/body/div[1]/div/div/div/div[1]/div/div[1]/div/div[1]/div[4]/button";
	public static String FixedInvoiceReversalVoucher="InvoiceNumber";
	public static String FixedInvoiceReversalReverse=".//*[@id='subform']/form/div[1]/div[3]/button";
	public static String InvoiceNumberTabInFixedInvoiceReversal=".//*[@id='1']/td[3]";
	public static String CheckBoxInFixedInvoiceReversal="jqg_Grid_1";
	public static String FixedInvoiceReversalGo="Go";
	public static String FixedInvoiceReversalDate=".//*[@id='ReversalDate']";
	public static String FixedInvoiceReversalReason="Reason";
	public static String FixedInvoiceReverseAfterReason="Generate";
	public static String VariableInvoicing="Variable";
	public static String payment="Payment";
	public static String paymentDate=".//*[@id='date']";
	public static String FinApartment="auto_ApartmentId";
	public static String Vouchertype=".//*[@id='auto_InvType']";
	public static String FinGo="Go";
	public static String PaymentTable=".//*[@id='frm-Payment']/div/div/div[2]/div[4]";
	public static String payNarration=".//*[@id='Narration']";
	public static String paybutton=".//*[@id='btnpay']";
	public static String TableRowId="tr";
	public static String TablecolumnId="td";
	public static String TagnameInputId="input";
	public static String Narration1=".//*[@id='Narration1']";
	public static String Facilityvoucher="Facility Booking";
	public static String TotalAmountClearedTabInFinVouchers=".//*[@id='1']/td[9]";
	public static String MaintainaceType="Maintenance Invoice";
	public static String VariableInvoiceReversal="html/body/div[1]/div/div/div/div[1]/div/div[1]/div/div[2]/div[4]/button";
	public static String InvoiceType=".//*[@id='auto_InvTypeS']";
	public static String AdvanceRow=".//*[@id='advrow']/td[4]/input";
	public static String AdvanceReverse=".//*[@id='RevAdv']";
	public static String Advancegrid1=".//*[@id='jqg_Grid1_1']";
	public static String Advancegrid2=".//*[@id='jqg_Grid1_2']";
	public static String Advancegrid3=".//*[@id='jqg_Grid1_3']";
	public static String ReverseAdvanceTable=".//*[@id='Grid1']/tbody";
	public static String ReverseReason="Reason";
	public static String Reason="Reversing advance amount of facility booking";
	public static String ReverseButton="Generate";
	public static String CalculationType1="Number of Days from billing date";
	public static String ManageFacilityHeadingpath="html/body/div[1]/div/div/div[1]/div[1]/h3";
	public static String ManageFacilityHeading="Manage Facilities";
	public static String PaymentNarration="pay";
	
	public static String RadioButtonInFinancePayments=".//*[@id='frm-Payment']/div/div/div[2]/div[4]/table/tbody/tr/td[1]/input";
	public static String AdvanceTab=".//*[@id='frm-Payment']/div/div/div[2]/div[4]/table/tbody/tr/td[6]/input[3]";
	public static String AdminProfile=".//*[@id='bs-example-navbar-collapse-1']/ul/li[4]/span/a";
	public static String TaxRadioButtonInAdminProfile=".//*[@id='ServiceTax']";
	public static String SaveButtonInAdmin=".//*[@id='btnSave']";
	public static String Waiveoff="WaiveOff";
	public static String WaiveOffTable=".//*[@id='frm-Payment']/div/div/div[2]/div[4]/table/tbody";
	public static String WaiveOffButton=".//*[@id='waiveoff']";
	public static String SelectGL=".//*[@id='auto_GL']";
	public static String GLtype1="Cash";
	public static String serviceTaxTxtbox="ServiceTaxPercent";
	public static String GeneralLedgerAccount=".//*[@id='502']/div/img";
	public static String AddGL=".//*[@id='Add']";
	public static String GLAccountName=".//*[@id='AccountName']";
	public static String GLDescriptionPath=".//*[@id='Description']";
	public static String GLDescriptionTxt="create new GL";
	public static String LedgerGroupId=".//*[@id='auto_LedgerGroupID']";
	public static String GLGroup1="Recurring Expenditure";
	public static String GLName="Travelling expenses1";
	public static String GLName1="Travelling expenses2";
	public static String SaveGL=".//*[@id='Ledger']/div/div[3]/button[1]";
	public static String DeleteGL=".//*[@id='Delete']";
	public static String AddmanualVoucher=".//*[@id='Add']";
	public static String VoucherDate=".//*[@id='VoucherDate']";
	public static String DebitPath=".//*[@id='Debit']";
	public static String ExtendButton=".//*[@id='Voucher']/div/div/div[2]/div/div[4]/table/tbody/tr/td[9]/button";
	public static String SaveVoucher=".//*[@id='Voucher']/div/div/div[3]/button[1]";
	public static String TravelGL="Travelling Expenses";
	public static String Export="html/body/div[1]/div/div/div[1]/div[2]/div[1]/div/div/div/table/tbody/tr/td[6]/div/button";
	public static String Exportpdf="html/body/div[1]/div/div/div[1]/div[2]/div[1]/div/div/div/table/tbody/tr/td[6]/div/ul/li[1]/a";
	public static String MemberGL="Block 2 - 3";
	public static String Filter=".//*[@id='setlink']";
	public static String FilterFromdate=".//*[@id='FromDate']";
	public static String FilterTodate=".//*[@id='ToDate']";
	public static String FilterGo=".//*[@id='btnGo']";
	public static String LedgerGroup=".//*[@id='501']/div/img";
	public static String AccountGroupNametxtbox=".//*[@id='LedgerGroupName']";
	public static String AccountGroupName="Expenses26";
	public static String LedgeraccountGroupNameTxtBox=".//*[@id='ledgerGrp']";
	public static String LedgeraccountGroupName="expenses";
	public static String AccountGroupNameSave=".//*[@id='btnSave']";
	public static String EditGroupName=".//*[@id='Edit']";
	public static String AccountGroupName2="expenses27";
	public static String TrialBalance="html/body/div[1]/div/div/ul/li/b[1]/a";
	public static String IncomeandExpenditure="html/body/div[1]/div/div/ul/li/b[3]/a";
	public static String Ledger="html/body/div[1]/div/div/ul/li/b[4]/a";
	public static String LedgerGroupDropdown=".//*[@id='auto_groups']";
	public static String LedgerGroupname="Income";
	public static String LedgerAccountDropdown=".//*[@id='auto_accounts']";
	public static String LedgerAccountName="Maintenance Charges";
	public static String LedgerGo=".//*[@id='Go']";
	public static String FinFilterGo=".//*[@id='btnGo']";
	public static String Narration=".//*[@id='Narration']";
	public static String VariableNarration=".//*[@id='Narration1']";
	public static String ReversalInvoiceNumbertab=".//*[@id='InvoiceNumber']";
	public static String ManualVoucherGLtxt=".//*[@id='auto_LedgerID']";
	public static String Credit=".//*[@id='Voucher']/div/div/div[2]/div/div[3]/table/tbody/tr[2]/td[8]/input";
	
	
	

}
